# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'MVPBase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking', '~> 3.2.1'
pod 'OCMock', '~> 3.4.3'
pod 'XcodeCoverage', '~> 1.3.1'
pod 'YYModel', '~> 1.0.4'
pod 'WebViewJavascriptBridge', '~> 6.0.3'

  # Pods for MVPBase

  target 'MVPBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVPBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
